#4.1
attach(chole)
plot(x1,y)
plot(x2,y)
l.1 = lm(y~x1)
l.2 = lm(y~x2)
l.3 = lm(y~x1+x2)
summary(l.3)
plot(y,residuals(l.3))
qqplot(y,residuals(l.3))
shapiro.test(residuals(l.3))       
library(lmtest)       
dwtest(l.3)
predict(l.3,newdata=data.frame(x1=400, x2=54))

#4.2
attach(city)
plot(x1,y)
plot(x2,y)
plot(x3,y)
l.city = lm(y~x1+x2+x3)
summary(l.city)
plot(y,resid(l.city))
qqplot(y,resid(l.city))
shapiro.test(resid(l.3))
dwtest(l.3)
predict(l.city,newdata=data.frame(x1=700, x2=27, x3=7.1))

#4.3
attach(fighter)
fighter$LFFD = log(fighter$FFD)
plot(LFFD,SPR)
plot(RGF,SPR)
plot(PLF,SPR)
plot(SLF,SPR)
l.fighter=lm(SPR~LFFD+RGF+PLF+SLF)
summary(l.fighter)
plot(SPR,resid(l.fighter))
qqplot(SPR,resid(l.fighter))
