#1
data(pressure)
plot(pressure$temperature,pressure$pressure)
l.pressure = lm(pressure$pressure~pressure$temperature)
abline(l.pressure)
new_press = log10(pressure$pressure)
l.pressure_new = lm(new_press ~ pressure$temperature)
plot(pressure$temperature,new_press)
abline(l.pressure_new)

#2
library(faraway)
data(aatemp)
attach(aatemp)
plot(year,temp)
l.temp = lm(temp~year)
abline(l.temp)
l.temp_2 = lm(log10(temp)~year)
plot(year,log10(temp))
abline(l.temp_2)
cor.test(year,temp)
l.temp_3 = lm(temp~year + I(year^2))
plot(year,temp)
abline(l.temp_3)
summary(l.temp_3)
summary(l.temp)

#3
attach(swiss)
l.swiss = lm(Fertility ~ Agriculture + Examination + Education + Catholic + Infant.Mortality)
library(lmtest)
dwtest(l.swiss)
shapiro.test(resid(l.swiss))
plot(Fertility,resid(l.swiss))
ls.diag(l.swiss)
library(MASS)
library(survival)
ncvTest(l.swiss)
h <- hat(model.matrix(l.swiss))
plot(h, type = "h", xlab="case index", main="leverage plot")
influence(l.swiss)
inflm.swiss <- influence.measures(l.swiss)
summary(inflm.swiss) 
inflm.fit   
outlierTest(l.swiss)
summary(l.swiss)

#4
library(car)
attach(table4_4_cholesterol)
l.chole = lm(y~x1 + x2, data = table4_4_cholesterol)
shapiro.test(resid(l.chole))
library(MASS)
library(survival)
ncvTest(l.chole)
h <- hat(model.matrix(l.chole))
plot(h, type = "h", xlab="case index", main="leverage plot")
influence(l.chole)
inflm.chole <- influence.measures(l.chole)
summary(inflm.chole) 
inflm.fit   
outlierTest(l.chole)
summary(l.chole)
