talented = table7_9_talented
attach(talented)
l.talented = lm(score ~ fatheriq + motheriq + speak + count + read + edutv + cartoons)
summary(l.talented)
anova(l.talented)
step(l.talented)
library(car)
vif_values = vif(l.talented)
plot(vif_values, main="VIF Values", ylab="VIF")
l.talented.1 = lm(score ~ fatheriq + motheriq + speak + count + edutv)
l.talented.2 = lm(score ~ fatheriq + motheriq + read + edutv + cartoons)
summary((l.talented.1))
summary(l.talented.2)
cor_matrix = cor(talented[, c("fatheriq", "motheriq", "speak", "count", "read", "edutv", "cartoons")])
corrplot(cor_matrix, method = "color")

l.talented.3 = lm(score ~ fatheriq + motheriq + read + edutv)
summary(l.talented.3)
l.talented.4 = lm(score ~ fatheriq + motheriq + read)
summary(l.talented.4)
library(leaps)
x<-cbind(fatheriq,motheriq,read,edutv)
lp<-leaps(x,score, method="Cp")
outlierTest(l.talented.4)
inflm <- influence.measures(l.talented.3)
summary(inflm) 
inflm.1 <- influence.measures(l.talented.3)
summary(inflm.1) 
talented = talented[c(-24,-33),]
attach(talented)
l.talented.4 = lm(score ~ fatheriq + motheriq + read)
summary(l.talented.4)
l.talented.3 = lm(score ~ fatheriq + motheriq + read + edutv)
summary(l.talented.3)
